name: Snyk Action

on: [push, pull_request]

jobs:
  security:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}