name: Snyk Action
on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
    - uses: snyk/actions/setup@master
    - name: Install dependencies
      run: npm install
    - name: Snyk test
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}