name: Example workflow for Node using Snyk 2
on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
      - name: Checkout Master
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}