name: Example workflow for Node using Snyk 2
on: push
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  sast-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk code test --org=b512ae7b-a90b-4f80-b767-f60206ea1138
        #env:
          #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}