name: Example workflow for Node using Snyk 2
on: push
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  sast-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Snyk Auth
        run: snyk auth
      - name: Run Snyk to check for vulnerabilities
        run: snyk code test 
        #env:
          #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}