name: Example workflow using Snyk
on: push
jobs:
  snyk-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        # with:
          # args: --org=b512ae7b-a90b-4f80-b767-f60206ea1138