name: Example workflow for Node using Snyk
on: push
jobs:
  sast-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      # - name: Auth with Snyk
        # run: snyk auth b512ae7b-a90b-4f80-b767-f60206ea1138 
      - name: auth
        run: snyk auth
      - name: Run Snyk to check for vulnerabilities
        run: snyk code test --all-projects --org=${{env.SNYK_TOKEN}}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}